[package]
name = "persister"
description = "Persist raw data"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
repr = { path = "../repr" }
byteorder = "1.3"

[dev-dependencies]
datadriven = "0.1"
serde_json = "1.0"
