[package]
name = "persister"
description = "Persist raw data"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.31"
byteorder = "1.3"
repr = { path = "../repr" }
csv = "1.1"

[dev-dependencies]
datadriven = "0.1"
serde_json = "1.0"
